# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-06 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lrms', '0003_auto_20180822_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='first_name',
            field=models.CharField(default='John', max_length=20),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='last_name',
            field=models.CharField(default='Nangoma', max_length=20),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner', to='lrms.OwnerProfile'),
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='lrms.OwnerProfile'),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='kin_relation',
            field=models.CharField(choices=[('gma', 'Grand Mother'), ('gda', 'Grand Father'), ('dad', 'Father'), ('mom', 'Mother'), ('sis', 'Sister'), ('bro', 'Brother'), ('unc', 'Uncle'), ('aun', 'Auntie'), ('cuz', 'Cousin'), ('son', 'Son'), ('dot', 'Daughter')], max_length=3, verbose_name='Relationship Of Next Of Kin'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
