# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-08 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lrms', '0005_auto_20180906_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='paid_by',
        ),
        migrations.AddField(
            model_name='payment',
            name='received_from',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payer', to='lrms.OwnerProfile'),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner', to='lrms.OwnerProfile'),
        ),
    ]
