# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-12 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrms', '0006_auto_20180908_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='balance',
            field=models.FloatField(default=0, verbose_name='Balance Due'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('R', 'Residential'), ('C', 'Commercial')], max_length=1, null=True),
        ),
    ]
