# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-15 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrms', '0007_auto_20180912_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerprofile',
            name='kin_relation',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='next_of_kin',
        ),
        migrations.AddField(
            model_name='property',
            name='successor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='successor_relation',
            field=models.CharField(choices=[('gma', 'Grand Mother'), ('gda', 'Grand Father'), ('dad', 'Father'), ('mom', 'Mother'), ('sis', 'Sister'), ('bro', 'Brother'), ('unc', 'Uncle'), ('aun', 'Auntie'), ('cuz', 'Cousin'), ('son', 'Son'), ('dot', 'Daughter')], max_length=3, null=True, verbose_name='Relationship Of Next Of Kin'),
        ),
    ]
