# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-08 08:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lrms', '0008_auto_20180915_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='address',
        ),
        migrations.AddField(
            model_name='property',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='added_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='nrc',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='successor_relation',
            field=models.CharField(choices=[('gma', 'Grand Mother'), ('gda', 'Grand Father'), ('dad', 'Father'), ('mom', 'Mother'), ('sis', 'Sister'), ('bro', 'Brother'), ('unc', 'Uncle'), ('aun', 'Auntie'), ('cuz', 'Cousin'), ('son', 'Son'), ('dot', 'Daughter')], max_length=3, null=True, verbose_name='Relationship With Next Of Kin'),
        ),
    ]
