# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-08 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrms', '0009_auto_20181008_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='local_authority',
            field=models.CharField(max_length=50),
        ),
    ]
