# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-12 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrms', '0010_auto_20181008_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='holding_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='successor_relation',
            field=models.CharField(choices=[('gma', 'Grand Mother'), ('gda', 'Grand Father'), ('dad', 'Father'), ('mom', 'Mother'), ('sis', 'Sister'), ('bro', 'Brother'), ('unc', 'Uncle'), ('aun', 'Auntie'), ('cuz', 'Cousin'), ('son', 'Son'), ('dot', 'Daughter')], default='son', max_length=3, null=True, verbose_name='Relationship With Next Of Kin'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('R', 'Residential'), ('C', 'Commercial')], default='R', max_length=1, null=True),
        ),
    ]
