# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-14 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrms', '0011_auto_20181012_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='balance',
            field=models.FloatField(null=True, verbose_name='Balance Due'),
        ),
    ]
