# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-14 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrms', '0012_auto_20181014_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='balance',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_number',
            field=models.CharField(default='elysian', max_length=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='balance',
            field=models.FloatField(default=0.0, verbose_name='Balance Due'),
            preserve_default=False,
        ),
    ]
