# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-14 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrms', '0015_auto_20181014_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_number',
            field=models.CharField(default='elysian', max_length=500),
        ),
    ]
